# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wsy/Documents/sh

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wsy/Documents/sh

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wsy/Documents/sh/CMakeFiles /home/wsy/Documents/sh//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wsy/Documents/sh/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xargs

# Build rule for target.
xargs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xargs
.PHONY : xargs

# fast build rule for target.
xargs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xargs.dir/build.make CMakeFiles/xargs.dir/build
.PHONY : xargs/fast

#=============================================================================
# Target rules for targets named ln

# Build rule for target.
ln: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ln
.PHONY : ln

# fast build rule for target.
ln/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ln.dir/build.make CMakeFiles/ln.dir/build
.PHONY : ln/fast

#=============================================================================
# Target rules for targets named mv

# Build rule for target.
mv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mv
.PHONY : mv

# fast build rule for target.
mv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mv.dir/build.make CMakeFiles/mv.dir/build
.PHONY : mv/fast

#=============================================================================
# Target rules for targets named cp

# Build rule for target.
cp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cp
.PHONY : cp

# fast build rule for target.
cp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/build
.PHONY : cp/fast

#=============================================================================
# Target rules for targets named mkdir

# Build rule for target.
mkdir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mkdir
.PHONY : mkdir

# fast build rule for target.
mkdir/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkdir.dir/build.make CMakeFiles/mkdir.dir/build
.PHONY : mkdir/fast

#=============================================================================
# Target rules for targets named rm

# Build rule for target.
rm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rm
.PHONY : rm

# fast build rule for target.
rm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rm.dir/build.make CMakeFiles/rm.dir/build
.PHONY : rm/fast

#=============================================================================
# Target rules for targets named touch

# Build rule for target.
touch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 touch
.PHONY : touch

# fast build rule for target.
touch/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/touch.dir/build.make CMakeFiles/touch.dir/build
.PHONY : touch/fast

#=============================================================================
# Target rules for targets named cat

# Build rule for target.
cat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cat
.PHONY : cat

# fast build rule for target.
cat/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cat.dir/build.make CMakeFiles/cat.dir/build
.PHONY : cat/fast

#=============================================================================
# Target rules for targets named ls

# Build rule for target.
ls: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ls
.PHONY : ls

# fast build rule for target.
ls/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/build
.PHONY : ls/fast

#=============================================================================
# Target rules for targets named sh

# Build rule for target.
sh: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sh
.PHONY : sh

# fast build rule for target.
sh/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/build
.PHONY : sh/fast

builtincmd/cd.o: builtincmd/cd.c.o

.PHONY : builtincmd/cd.o

# target to build an object file
builtincmd/cd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/builtincmd/cd.c.o
.PHONY : builtincmd/cd.c.o

builtincmd/cd.i: builtincmd/cd.c.i

.PHONY : builtincmd/cd.i

# target to preprocess a source file
builtincmd/cd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/builtincmd/cd.c.i
.PHONY : builtincmd/cd.c.i

builtincmd/cd.s: builtincmd/cd.c.s

.PHONY : builtincmd/cd.s

# target to generate assembly for a file
builtincmd/cd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/builtincmd/cd.c.s
.PHONY : builtincmd/cd.c.s

builtincmd/echo.o: builtincmd/echo.c.o

.PHONY : builtincmd/echo.o

# target to build an object file
builtincmd/echo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/builtincmd/echo.c.o
.PHONY : builtincmd/echo.c.o

builtincmd/echo.i: builtincmd/echo.c.i

.PHONY : builtincmd/echo.i

# target to preprocess a source file
builtincmd/echo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/builtincmd/echo.c.i
.PHONY : builtincmd/echo.c.i

builtincmd/echo.s: builtincmd/echo.c.s

.PHONY : builtincmd/echo.s

# target to generate assembly for a file
builtincmd/echo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/builtincmd/echo.c.s
.PHONY : builtincmd/echo.c.s

builtincmd/exit.o: builtincmd/exit.c.o

.PHONY : builtincmd/exit.o

# target to build an object file
builtincmd/exit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/builtincmd/exit.c.o
.PHONY : builtincmd/exit.c.o

builtincmd/exit.i: builtincmd/exit.c.i

.PHONY : builtincmd/exit.i

# target to preprocess a source file
builtincmd/exit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/builtincmd/exit.c.i
.PHONY : builtincmd/exit.c.i

builtincmd/exit.s: builtincmd/exit.c.s

.PHONY : builtincmd/exit.s

# target to generate assembly for a file
builtincmd/exit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/builtincmd/exit.c.s
.PHONY : builtincmd/exit.c.s

builtincmd/export.o: builtincmd/export.c.o

.PHONY : builtincmd/export.o

# target to build an object file
builtincmd/export.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/builtincmd/export.c.o
.PHONY : builtincmd/export.c.o

builtincmd/export.i: builtincmd/export.c.i

.PHONY : builtincmd/export.i

# target to preprocess a source file
builtincmd/export.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/builtincmd/export.c.i
.PHONY : builtincmd/export.c.i

builtincmd/export.s: builtincmd/export.c.s

.PHONY : builtincmd/export.s

# target to generate assembly for a file
builtincmd/export.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/builtincmd/export.c.s
.PHONY : builtincmd/export.c.s

builtincmd/kill.o: builtincmd/kill.c.o

.PHONY : builtincmd/kill.o

# target to build an object file
builtincmd/kill.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/builtincmd/kill.c.o
.PHONY : builtincmd/kill.c.o

builtincmd/kill.i: builtincmd/kill.c.i

.PHONY : builtincmd/kill.i

# target to preprocess a source file
builtincmd/kill.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/builtincmd/kill.c.i
.PHONY : builtincmd/kill.c.i

builtincmd/kill.s: builtincmd/kill.c.s

.PHONY : builtincmd/kill.s

# target to generate assembly for a file
builtincmd/kill.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/builtincmd/kill.c.s
.PHONY : builtincmd/kill.c.s

builtincmd/pwd.o: builtincmd/pwd.c.o

.PHONY : builtincmd/pwd.o

# target to build an object file
builtincmd/pwd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/builtincmd/pwd.c.o
.PHONY : builtincmd/pwd.c.o

builtincmd/pwd.i: builtincmd/pwd.c.i

.PHONY : builtincmd/pwd.i

# target to preprocess a source file
builtincmd/pwd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/builtincmd/pwd.c.i
.PHONY : builtincmd/pwd.c.i

builtincmd/pwd.s: builtincmd/pwd.c.s

.PHONY : builtincmd/pwd.s

# target to generate assembly for a file
builtincmd/pwd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/builtincmd/pwd.c.s
.PHONY : builtincmd/pwd.c.s

filecmd/cat.o: filecmd/cat.c.o

.PHONY : filecmd/cat.o

# target to build an object file
filecmd/cat.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cat.dir/build.make CMakeFiles/cat.dir/filecmd/cat.c.o
.PHONY : filecmd/cat.c.o

filecmd/cat.i: filecmd/cat.c.i

.PHONY : filecmd/cat.i

# target to preprocess a source file
filecmd/cat.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cat.dir/build.make CMakeFiles/cat.dir/filecmd/cat.c.i
.PHONY : filecmd/cat.c.i

filecmd/cat.s: filecmd/cat.c.s

.PHONY : filecmd/cat.s

# target to generate assembly for a file
filecmd/cat.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cat.dir/build.make CMakeFiles/cat.dir/filecmd/cat.c.s
.PHONY : filecmd/cat.c.s

filecmd/cp.o: filecmd/cp.c.o

.PHONY : filecmd/cp.o

# target to build an object file
filecmd/cp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/filecmd/cp.c.o
.PHONY : filecmd/cp.c.o

filecmd/cp.i: filecmd/cp.c.i

.PHONY : filecmd/cp.i

# target to preprocess a source file
filecmd/cp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/filecmd/cp.c.i
.PHONY : filecmd/cp.c.i

filecmd/cp.s: filecmd/cp.c.s

.PHONY : filecmd/cp.s

# target to generate assembly for a file
filecmd/cp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/filecmd/cp.c.s
.PHONY : filecmd/cp.c.s

filecmd/ln.o: filecmd/ln.c.o

.PHONY : filecmd/ln.o

# target to build an object file
filecmd/ln.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ln.dir/build.make CMakeFiles/ln.dir/filecmd/ln.c.o
.PHONY : filecmd/ln.c.o

filecmd/ln.i: filecmd/ln.c.i

.PHONY : filecmd/ln.i

# target to preprocess a source file
filecmd/ln.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ln.dir/build.make CMakeFiles/ln.dir/filecmd/ln.c.i
.PHONY : filecmd/ln.c.i

filecmd/ln.s: filecmd/ln.c.s

.PHONY : filecmd/ln.s

# target to generate assembly for a file
filecmd/ln.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ln.dir/build.make CMakeFiles/ln.dir/filecmd/ln.c.s
.PHONY : filecmd/ln.c.s

filecmd/ls.o: filecmd/ls.c.o

.PHONY : filecmd/ls.o

# target to build an object file
filecmd/ls.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/filecmd/ls.c.o
.PHONY : filecmd/ls.c.o

filecmd/ls.i: filecmd/ls.c.i

.PHONY : filecmd/ls.i

# target to preprocess a source file
filecmd/ls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/filecmd/ls.c.i
.PHONY : filecmd/ls.c.i

filecmd/ls.s: filecmd/ls.c.s

.PHONY : filecmd/ls.s

# target to generate assembly for a file
filecmd/ls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/filecmd/ls.c.s
.PHONY : filecmd/ls.c.s

filecmd/mkdir.o: filecmd/mkdir.c.o

.PHONY : filecmd/mkdir.o

# target to build an object file
filecmd/mkdir.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkdir.dir/build.make CMakeFiles/mkdir.dir/filecmd/mkdir.c.o
.PHONY : filecmd/mkdir.c.o

filecmd/mkdir.i: filecmd/mkdir.c.i

.PHONY : filecmd/mkdir.i

# target to preprocess a source file
filecmd/mkdir.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkdir.dir/build.make CMakeFiles/mkdir.dir/filecmd/mkdir.c.i
.PHONY : filecmd/mkdir.c.i

filecmd/mkdir.s: filecmd/mkdir.c.s

.PHONY : filecmd/mkdir.s

# target to generate assembly for a file
filecmd/mkdir.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkdir.dir/build.make CMakeFiles/mkdir.dir/filecmd/mkdir.c.s
.PHONY : filecmd/mkdir.c.s

filecmd/mv.o: filecmd/mv.c.o

.PHONY : filecmd/mv.o

# target to build an object file
filecmd/mv.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mv.dir/build.make CMakeFiles/mv.dir/filecmd/mv.c.o
.PHONY : filecmd/mv.c.o

filecmd/mv.i: filecmd/mv.c.i

.PHONY : filecmd/mv.i

# target to preprocess a source file
filecmd/mv.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mv.dir/build.make CMakeFiles/mv.dir/filecmd/mv.c.i
.PHONY : filecmd/mv.c.i

filecmd/mv.s: filecmd/mv.c.s

.PHONY : filecmd/mv.s

# target to generate assembly for a file
filecmd/mv.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mv.dir/build.make CMakeFiles/mv.dir/filecmd/mv.c.s
.PHONY : filecmd/mv.c.s

filecmd/rm.o: filecmd/rm.c.o

.PHONY : filecmd/rm.o

# target to build an object file
filecmd/rm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rm.dir/build.make CMakeFiles/rm.dir/filecmd/rm.c.o
.PHONY : filecmd/rm.c.o

filecmd/rm.i: filecmd/rm.c.i

.PHONY : filecmd/rm.i

# target to preprocess a source file
filecmd/rm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rm.dir/build.make CMakeFiles/rm.dir/filecmd/rm.c.i
.PHONY : filecmd/rm.c.i

filecmd/rm.s: filecmd/rm.c.s

.PHONY : filecmd/rm.s

# target to generate assembly for a file
filecmd/rm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rm.dir/build.make CMakeFiles/rm.dir/filecmd/rm.c.s
.PHONY : filecmd/rm.c.s

filecmd/touch.o: filecmd/touch.c.o

.PHONY : filecmd/touch.o

# target to build an object file
filecmd/touch.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/touch.dir/build.make CMakeFiles/touch.dir/filecmd/touch.c.o
.PHONY : filecmd/touch.c.o

filecmd/touch.i: filecmd/touch.c.i

.PHONY : filecmd/touch.i

# target to preprocess a source file
filecmd/touch.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/touch.dir/build.make CMakeFiles/touch.dir/filecmd/touch.c.i
.PHONY : filecmd/touch.c.i

filecmd/touch.s: filecmd/touch.c.s

.PHONY : filecmd/touch.s

# target to generate assembly for a file
filecmd/touch.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/touch.dir/build.make CMakeFiles/touch.dir/filecmd/touch.c.s
.PHONY : filecmd/touch.c.s

filecmd/xargs.o: filecmd/xargs.c.o

.PHONY : filecmd/xargs.o

# target to build an object file
filecmd/xargs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xargs.dir/build.make CMakeFiles/xargs.dir/filecmd/xargs.c.o
.PHONY : filecmd/xargs.c.o

filecmd/xargs.i: filecmd/xargs.c.i

.PHONY : filecmd/xargs.i

# target to preprocess a source file
filecmd/xargs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xargs.dir/build.make CMakeFiles/xargs.dir/filecmd/xargs.c.i
.PHONY : filecmd/xargs.c.i

filecmd/xargs.s: filecmd/xargs.c.s

.PHONY : filecmd/xargs.s

# target to generate assembly for a file
filecmd/xargs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xargs.dir/build.make CMakeFiles/xargs.dir/filecmd/xargs.c.s
.PHONY : filecmd/xargs.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/main.c.s
.PHONY : main.c.s

src/defines.o: src/defines.c.o

.PHONY : src/defines.o

# target to build an object file
src/defines.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/src/defines.c.o
.PHONY : src/defines.c.o

src/defines.i: src/defines.c.i

.PHONY : src/defines.i

# target to preprocess a source file
src/defines.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/src/defines.c.i
.PHONY : src/defines.c.i

src/defines.s: src/defines.c.s

.PHONY : src/defines.s

# target to generate assembly for a file
src/defines.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/src/defines.c.s
.PHONY : src/defines.c.s

src/getline.o: src/getline.c.o

.PHONY : src/getline.o

# target to build an object file
src/getline.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/src/getline.c.o
.PHONY : src/getline.c.o

src/getline.i: src/getline.c.i

.PHONY : src/getline.i

# target to preprocess a source file
src/getline.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/src/getline.c.i
.PHONY : src/getline.c.i

src/getline.s: src/getline.c.s

.PHONY : src/getline.s

# target to generate assembly for a file
src/getline.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/src/getline.c.s
.PHONY : src/getline.c.s

src/io.o: src/io.c.o

.PHONY : src/io.o

# target to build an object file
src/io.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/src/io.c.o
.PHONY : src/io.c.o

src/io.i: src/io.c.i

.PHONY : src/io.i

# target to preprocess a source file
src/io.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/src/io.c.i
.PHONY : src/io.c.i

src/io.s: src/io.c.s

.PHONY : src/io.s

# target to generate assembly for a file
src/io.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sh.dir/build.make CMakeFiles/sh.dir/src/io.c.s
.PHONY : src/io.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cat"
	@echo "... cp"
	@echo "... ln"
	@echo "... ls"
	@echo "... mkdir"
	@echo "... mv"
	@echo "... rm"
	@echo "... sh"
	@echo "... touch"
	@echo "... xargs"
	@echo "... builtincmd/cd.o"
	@echo "... builtincmd/cd.i"
	@echo "... builtincmd/cd.s"
	@echo "... builtincmd/echo.o"
	@echo "... builtincmd/echo.i"
	@echo "... builtincmd/echo.s"
	@echo "... builtincmd/exit.o"
	@echo "... builtincmd/exit.i"
	@echo "... builtincmd/exit.s"
	@echo "... builtincmd/export.o"
	@echo "... builtincmd/export.i"
	@echo "... builtincmd/export.s"
	@echo "... builtincmd/kill.o"
	@echo "... builtincmd/kill.i"
	@echo "... builtincmd/kill.s"
	@echo "... builtincmd/pwd.o"
	@echo "... builtincmd/pwd.i"
	@echo "... builtincmd/pwd.s"
	@echo "... filecmd/cat.o"
	@echo "... filecmd/cat.i"
	@echo "... filecmd/cat.s"
	@echo "... filecmd/cp.o"
	@echo "... filecmd/cp.i"
	@echo "... filecmd/cp.s"
	@echo "... filecmd/ln.o"
	@echo "... filecmd/ln.i"
	@echo "... filecmd/ln.s"
	@echo "... filecmd/ls.o"
	@echo "... filecmd/ls.i"
	@echo "... filecmd/ls.s"
	@echo "... filecmd/mkdir.o"
	@echo "... filecmd/mkdir.i"
	@echo "... filecmd/mkdir.s"
	@echo "... filecmd/mv.o"
	@echo "... filecmd/mv.i"
	@echo "... filecmd/mv.s"
	@echo "... filecmd/rm.o"
	@echo "... filecmd/rm.i"
	@echo "... filecmd/rm.s"
	@echo "... filecmd/touch.o"
	@echo "... filecmd/touch.i"
	@echo "... filecmd/touch.s"
	@echo "... filecmd/xargs.o"
	@echo "... filecmd/xargs.i"
	@echo "... filecmd/xargs.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/defines.o"
	@echo "... src/defines.i"
	@echo "... src/defines.s"
	@echo "... src/getline.o"
	@echo "... src/getline.i"
	@echo "... src/getline.s"
	@echo "... src/io.o"
	@echo "... src/io.i"
	@echo "... src/io.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

